server:
  port: 13000
spring:
  profiles:
    include: sharding

  redis:
    host: 192.168.220.130
    password: MewGulf1314
    lettuce:
      pool:
        max-active: 16
        min-idle: 0
  rabbitmq:
    host: 192.168.220.130
    port: 5672
    username: admin
    password: admin
    virtualHost: /
    #开启接收端(exchange->consumer)回调
    publisherReturns: true
    #发送端(producer->exchange)确认,开启发送端错误回调
    publisherConfirmType: CORRELATED
    listener:
      type: SIMPLE
      simple:
        #开启ack手动确认
        acknowledge-mode: manual




app:
  props:
    ware-url: http://localhost:14000
