server:
  port: 13000
spring:
  profiles:
    include: sharding

  redis:
    host: 192.168.220.130
    password: MewGulf1314
    lettuce:
      pool:
        max-active: 16
        min-idle: 0

app:
  props:
    ware-url: http://localhost:14000
