server:
  port: 80
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*" #允许所有ip跨域访问
            allowedMethods: "*" #允许所有请求方法
            allowedHeaders: "*" #允许携带请求头
            allowCredentials: true #允许携带cookie
      routes:
        - id: service-product
          uri: lb://service-product
          predicates:
            - Path=/admin/product/**
        - id: web_all
          uri: lb://web-all
          predicates:
            - Host=**.gmall.com,gmall.com