server:
  port: 8000


spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
feign:
  client:
    config:
      default:
        connection-timeout: 5000
        read-timeout: 100000
        #retryer: org.springframework.cloud.sleuth.instrument.web.client.feign.NeverRetry
