server:
  port: 8000


spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
feign:
  client:
    config:
      service-item:
        connection-timeout: 5000
        read-timeout: 100000
