server:
  port: 11000

spring:
  redis:
    host: 192.168.220.130
    password: MewGulf1314
    jedis:
      pool:
        max-active: 8
        min-idle: 0
  profiles:
    include: sharding

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml