server:
  port: 7000


spring:
  datasource:
    url: jdbc:mysql://192.168.220.130:3306/gmall_product?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.220.130
    password: MewGulf1314
    jedis:
      pool:
        max-active: 8
        min-idle: 0

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

app:
  minio:
    endpoint: http://192.168.220.130:9000/
    accessKey: admin
    secertKey: admin123456
    bucket: gmall
  threadpool:
    corePoolSize: 8
    maximumPoolSize: 16
    keepAliveTime: 1
    queueNumber: 1000
